spring:
  application:
    name: Student Forums 413
    security:
      key: e731943f7781ccdd9b10a08d392bc7fe69c51037ba42044cae7d485dbff15052
  datasource:
    url: jdbc:mysql://localhost:3306/forum_project?useSSL=false&allowPublicKeyRetrieval=true
    username: projectadmin # the mysql user details
    password: project12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter=DEBUG:
#logging:
#  level:
#    org:
#      springframework: DEBUG

# checking health and metrics of metrics
# spring.servlet.multipart.max-file-size=50MB
#spring.servlet.multipart.max-request-size=50MB
management:
  info:
    java:
      enabled: true
    env:
      enabled: true
  server:
    port: 8080
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
info:
  application:
    name: ${spring.application.name}
    description: Very cool Spring Boot application
    version: '@project.version@'
    spring-boot-version: '@project.parent.version@'
